# Generated by Django 5.0.6 on 2024-05-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadministrador', models.AutoField(db_column='idAdministrador', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cpf', models.IntegerField(db_column='CPF')),
                ('senha', models.CharField(db_column='Senha', max_length=16)),
                ('email', models.CharField(db_column='Email', max_length=45)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('idapartamento', models.AutoField(db_column='idApartamento', primary_key=True, serialize=False)),
                ('bloco', models.IntegerField(db_column='Bloco')),
                ('numero', models.IntegerField(db_column='Numero')),
            ],
            options={
                'db_table': 'apartamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('idcondominio', models.AutoField(db_column='idCondominio', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('cnpj', models.IntegerField(db_column='CNPJ')),
                ('rua', models.CharField(db_column='Rua', max_length=45)),
                ('numero', models.IntegerField(db_column='Numero')),
                ('complemento', models.CharField(db_column='Complemento', max_length=20)),
                ('bairro', models.CharField(db_column='Bairro', max_length=45)),
                ('cep', models.IntegerField(db_column='CEP')),
                ('cidade', models.CharField(db_column='Cidade', max_length=45)),
                ('estado', models.CharField(db_column='Estado', max_length=20)),
            ],
            options={
                'db_table': 'condominio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('idmorador', models.AutoField(db_column='idMorador', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF')),
                ('telefone', models.IntegerField(db_column='Telefone')),
                ('email', models.CharField(db_column='Email', max_length=45)),
            ],
            options={
                'db_table': 'morador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('idproprietario', models.AutoField(db_column='idProprietario', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cpf', models.IntegerField(db_column='CPF')),
                ('telefone', models.IntegerField(db_column='Telefone')),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('rua', models.CharField(db_column='Rua', max_length=45)),
                ('numero', models.IntegerField(db_column='Numero')),
                ('complemento', models.CharField(db_column='Complemento', max_length=45)),
                ('bairro', models.CharField(db_column='Bairro', max_length=45)),
                ('cep', models.IntegerField(db_column='CEP')),
                ('cidade', models.CharField(db_column='Cidade', max_length=45)),
                ('estado', models.CharField(db_column='Estado', max_length=20)),
            ],
            options={
                'db_table': 'proprietario',
                'managed': False,
            },
        ),
    ]
